inputs:
  args:
    description: 'Arguments for the CLI command'
    required: true
  cli:
    description: 'cli command to run (gcloud and gsutil available)'
    default: 'gcloud'
    required: false
