steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'test'
  args: ['functions',
  'deploy',
  'myfunction',
  '--runtime=nodejs10',
  '--trigger-http',
  '--entry-point=screening',
  '--region=us-central1',
  '--source=./'
  '--allow-unauthenticated']
