steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'myfunction'
  args: ['functions',
  'deploy',
  'myfunction',
  '--runtime=nodejs10',
  '--trigger-http',
  '--entry-point=screening',
  '--region=us-central1',
  '--source=./',
  '--allow-unauthenticated',
  '--trigger-resource=striking-center-273318.appspot.com',
  '--trigger-event google.storage.object.archive']
