steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - myfunction
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=nodejs10
  - --allow-unauthenticated
  - --entry-point=screening
